switch (dishno)
        {
            case 1:
                System.out.println("The rate for pasta is Rs.100");
                break;
            case 2:
                System.out.println("The rate for Lasagna is Rs.150");
                break;
            case 3:
                System.out.println("The rate for Pizza is Rs.120");
                break;   
            case 4:
                System.out.println("The rate for Garlic Bread is Rs.90");
                break;    
            case 5:
                System.out.println("The rate for Pav Bhaji is Rs.110");
                break;  
            case 6:
                System.out.println("The rate for Dosa is Rs.60");
                break;    
            case 7:
                System.out.println("The rate for Momos is Rs.100");
                break;    
            case 8:
                System.out.println("The rate for Noodels is Rs.80");
                break;    
            case 9:
                System.out.println("The rate for Fried Rice is Rs.120");
                break;    
            case 10:
                System.out.println("The rate for Sizler is Rs.200");
                break;  
            default:
                System.out.println("Wrong Choice");
        }
    }
}